[Server]
IP = "0.0.0.0"
PORT = 8080
#是否开启本地tls
EnableTLS = false
#tls证书路径
TLSCertPath = ""
#tls密钥路径
TLSKeyPath = ""
# admininfo默认登录
AdminInfo = {username="admin",password="admin"}
# 接口调用token
ApiAuthToken = "this-is-a-real-auth-token"


[JavbusSite]
#是否开启代理访问
EnableProxy = false
#代理地址 支持http代理 https代理 和sock5代理
#格式 "socks5://username:password@host:port"
#格式 "http://username:password@host:port"
#格式 "https://username:password@host:port"
ProxyUrl = "socks5://username:password@host:port"
#Javbus网址列表
JavbusUrls = ["https://www.javbus.com/","https://www.seejav.bid/"]
#浏览器user-agent列表
UserAgents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15",
]
#javbus网站用户cookies
#只需要填写cookies字段就可以了
UserCookies = [
    {username="user1",cookies=""},
    {username="user2",cookies=""},
    {username="user3",cookies=""},
]
